services:
  onetick-frontend:
    build:
      context: ./../../frontend
      dockerfile: Dockerfile.ssr
    container_name: onetick-frontend
    ports:
      - "8125:80"
    environment:
      VITE_STRIPE_PUBLISHABLE_KEY: ""
      VITE_API_URL_SERVER: "http://localhost/api"
      VITE_API_URL_CLIENT: "https://app.onetick/api"
      VITE_FRONTEND_URL: "https://app.onetick"